### ISSUE TITLE
question: why making an own library

### ISSUE THREAD

**Issue by maapteh** [sverweij/upem#12]
your team uses yarn, why not run `yarn upgrade-interactive --latest` ?

nice work though :)

**Comment by sverweij** [comment]
hey @maapteh LTNS! 

I wrote this script as a last resort for as nothing I could find out there fitted the needs of the packages I maintain (dependency-cruiser, state-machine-cat, mscgen.js, some atom plugins):
- The public packages I maintain still primarily rely on npm (apm for the plugins) and don't have lock files (might seem an odd choice, but it was made deliberately). 
- For some of them I need dependencies to be ignored on automatic upgrades. Typically this need arrises when nodejs.org de-supports an older version and upstream deps go along with that, while the packages still support that version.

That said - if there's something out there that fits my use case I'll deprecate up'em in an instant. 

Everyone on yarn should probably be using yarn's upgrade/ upgrade-interactive instead of up'em though. Or instead of renovate/ greenkeeper/ npm-check/ npm-check-updates for that matter. And that includes my team (which idd doesn't use upem :-) ).

**Comment by maapteh** [comment]
ok :)
